# Generated by Django 2.1.1 on 2018-09-19 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('payroll', '0004_auto_20180918_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesigDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Departments')),
            ],
            options={
                'verbose_name_plural': 'DesigDept',
                'db_table': 'DesigDept',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Project',
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=None, to='payroll.Project')),
            ],
            options={
                'verbose_name_plural': 'Team',
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Project')),
            ],
            options={
                'verbose_name_plural': 'UserProject',
                'db_table': 'UserProject',
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Team')),
            ],
            options={
                'verbose_name_plural': 'UserTeam',
                'db_table': 'UserTeam',
            },
        ),
        migrations.RemoveField(
            model_name='roledept',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='roledept',
            name='role_id',
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name_plural': 'Designations'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dept_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.AlterModelTable(
            name='designation',
            table='Designations',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Designation',
        ),
        migrations.DeleteModel(
            name='RoleDept',
        ),
        migrations.AddField(
            model_name='userteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desigdept',
            name='desig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Designation'),
        ),
    ]
